### ISSUE TITLE
Data races

### ISSUE THREAD

**Issue by jan-wassenberg** [mm2/Little-CMS#170] opened 2018-07-26 09:14 UTC
Hi, thank you for lcms!
FYI tsan (thread sanitizer) from clang reports two race conditions
in multithreaded code that opens and creates profiles:

```  Write of size 8 at 0x7f3a9ec4dc38 by thread T10:
    #0 cmsCreateProfilePlaceholder src/cmsio0.c:504 

  Previous write of size 8 at 0x7f3a9ec4dc38 by thread T7:
    #0 gmtime
    #1 cmsCreateProfilePlaceholder src/cmsio0.c:504
```

gmtime is not re-entrant because it uses static data. Would gmtime_r be an option?

The second is more straightforward:
```  Write of size 8 at 0x7fbbf621f5e0 by thread T6 (mutexes: write M2734):
    #0 cmsXYZ2xyY src/cmspcs.c:99
    #1 cmsD50_xyY src/cmswtpnt.c:42
    #2 cmsCreateXYZProfileTHR src/cmsvirt.c:572

  Previous write of size 8 at 0x7fbbf621f5e0 by thread T7:
    #0 cmsXYZ2xyY src/cmspcs.c:99
    #1 cmsD50_xyY src/cmswtpnt.c:42
    #2 cmsCreateLab2ProfileTHR src/cmsvirt.c:479
```

Again we have shared static data in
```
const cmsCIExyY* cmsD50_xyY() {
    static cmsCIExyY D50xyY;
    cmsXYZ2xyY(&D50xyY, cmsD50_XYZ());
```

As a workaround, we can just take a lock around all transform/profile creation functions, though that's a bit disappointing given their THR suffix.

**Comment by DominikDeak** [comment] 2020-06-05 08:29
> As a workaround, we can just take a lock around all transform/profile creation functions, though that's a bit disappointing given their THR suffix.

I don't think think Little CMS API calls are designed to be thread safe as a shared resource, even if you use THR suffix.

I suggest you to create a CMS context separately as a thread local resource and then work on profiles that way. Don't share them between threads.

**Comment by jan-wassenberg** [comment] 2020-06-05 09:16
Thanks for the suggestion. We do use [thread-local contexts](https://gitlab.com/wg1/jpeg-xl/-/blob/master/jxl/color_management.cc#L1447), the issue seems to be that lcms has shared mutable state (e.g. D50xyY) outside the contexts.

**Comment by mm2** [comment] 2020-06-05 10:58
D50xyY is a constant value computed from another constant. Since c99 has not constexpr, the compiler/optimizer has no clue about D50xyY being constant. I can change source to that value, but it's not nice to have data duplicity.

Regarding gmtime, I'm searching for portable alternatives.

**Comment by mm2** [comment] 2020-06-05 11:17
> I don't think think Little CMS API calls are designed to be thread safe as a shared resource, even if you use THR suffix.

Could you please submit a piece of code that demostrates a data race when  transforming pixels? I cannot reproduce any error.

Thanks

**Comment by jan-wassenberg** [comment] 2020-06-08 13:19
@mm2 Thanks for looking into this.

It is a bit difficult to reproduce the original problem. The [JPEG XL test suite](https://gitlab.com/wg1/jpeg-xl/-/blob/master/doc/developing_in_docker.md) mostly passes under tsan even if I remove all instances of the [LCMS mutex](https://gitlab.com/wg1/jpeg-xl/-/blob/master/jxl/color_management.cc#L466):

`BUILD_DIR=build_tsan CC=clang-7 CXX=clang++-7 SKIP_TEST=1 ./ci.sh tsan`

build_tsan/tests/passes_test fails, with the following data race:
```
  Read of size 8 at 0x7b300001c2c0 by thread T11:
    #0 _cmsGetContext lcms/src/cmsplugin.c (passes_test+0x14c4a36)
    #1 _cmsContextGetClientChunk lcms/src/cmsplugin.c:707 (passes_test+0x14c4a36)
    #2 _cmsMallocZero lcms/src/cmserr.c:273:61 (passes_test+0x1472bb0)
    #3 cmsCreateProfilePlaceholder lcms/src/cmsio0.c:492:45 (passes_test+0x1493407)

  Previous write of size 8 at 0x7b300001c2c0 by thread T6:
    #0 malloc <null> (passes_test+0x465e6c)
    #1 _cmsMallocDefaultFn lcms/src/cmserr.c:97:20 (passes_test+0x1471dbf)
    #2 _cmsMalloc lcms/src/cmserr.c:267:12 (passes_test+0x1472b42)
    #3 cmsCreateContext lcms/src/cmsplugin.c:801:40 (passes_test+0x14c4d16)
```

**Comment by mm2** [comment] 2020-06-08 14:48
Hello,Excellent!Seems you managed to find a rare case where there is a race condition. inspecting the sources, contexts are stored as a linked list, and adding/deleting nodes is protected with a mutex. BUT, searching a context across this list is not protected. This works most of times because the nodes are added touching only the list head. So in the  case a context is created by a thread whilst other theads do heavy search on the list *may* end in a data race. I will try to do a fix but I will first create a piece of code that fully reproduces the problem. BTW you should not need any external mutex once this is solved.Thanks again.

**Comment by jan-wassenberg** [comment] 2020-06-08 15:06
Thanks again for looking into this! Yes, sanitizers can be really helpful for catching these rare corner cases.
Sounds good, thanks for the tip about the mutex, I'll look forward to removing it later.

**Comment by mm2** [comment] 2021-06-20 09:09
Since #263 fixes the remaining cases, I'm now closing the issue.

**Closed by mm2** 2021-06-20 09:09 UTC
