### ISSUE TITLE
Consider prequantizing colorants to 16bit fixed point.

### ISSUE THREAD

**Issue by therahedwig** [mm2/Little-CMS#248] opened 2021-03-11 11:56 UTC
So, we, Krita, have this [odd bug](https://bugs.kde.org/show_bug.cgi?id=422267).

Basically, Elle Stone once made icc profiles after coming across an issue with [prequantization of the colorants](https://ninedegreesbelow.com/photography/well-behaved-profiles-quest.html#hexadecimal-quantization) leading to rounding errors. Whenever we use that profile, we don't seem to have roundtripping errors like above. However, the build-in sRGB profile doesn't have prequantized values, leading to roundtripping issues like the bug report above.

We know that Argyll has the code for this in the MIT-licensed icc.c, so we tried that, but it doesn't seem to work for us, and it may be that we're just not taking into account the chromatic adaptation. At this point however, I figured that it might just be better to make a bugreport, because all ICC profiles have 16bit fixed floating point hexadecimal quantization, so it might just make more sense to let LittleCMS take care of it?

**Comment by mm2** [comment] 2021-03-11 14:26
Thanks for contacting me. I will take a look to the issue. Regarding the web page on prequantization, I already know that article, but I have discarded it because some of the premises they claim are not really true. If you use the sRGB built-in in unbounded (float) mode, then the roundtrip is perfect. If I change the primaries to benefit 8 bit roundtrip I am damaging the float part. On 8 bit the accuracy is already poor and visually the error is not noticeable, so I choosed to favour float transforms and honour the colorants user is giving. 
On the other hand, this web proposes to use a pre-quantized white point for D50, that would be nice, but unfortunately the ICC spect says exactly what the D50 values should be, and are not those numbers. Diverging from spec would be a very bad move from my part, despite the questionable benefits. That should be addressed at ICC level, not in the implementations.
Anyway I will take a look, just to see if rountripping over and over keeps moving the color. If so (which seems the case) I would add a roundoff correction to prevent that.

**Comment by therahedwig** [comment] 2021-03-11 14:29
Thanks for considering it! Our problem in that bugreport seems to happen in 16bit integer, not 8bit, if that makes a difference.

**Comment by mm2** [comment] 2021-03-21 15:57
Ok, I have written a small piece of code to check whatever this is real. The program goes back and forth from sRGB to Lab and then uses the obtained rgb to do another iteration. It does 1000 iterations per sample. And then it checks all sRGB gamut doing 16 slices per component. The precision used is 16 bits RGB. Lab comes as doubles. 

Then the maximum error I got (maximum euclidean distance) after 1000 iterations is 18.05, which I think is a pretty good result, given that this is in 16-bits units. 

For what it seems, the pre-quantization is not needed and the built-in sRGB does a good job when round-tripping. Or maybe there is something wrong with this test code? Please double-check it...

```
static
double distance(const cmsUInt16Number* a, const cmsUInt16Number* b)
{
    double d1 = a[0] - b[0];
    double d2 = a[1] - b[1];
    double d3 = a[2] - b[2];

    return sqrt(d1 * d1 + d2 * d2 + d3 * d3);
}

int Check_sRGB_Rountrips(void)
{
    cmsUInt16Number rgb[3], seed[3];
    cmsCIELab Lab;
    int i, r, g, b;
    double err, maxErr;
    cmsHPROFILE hsRGB = cmsCreate_sRGBProfile();
    cmsHPROFILE hLab = cmsCreateLab4Profile(NULL);

    cmsHTRANSFORM hBack = cmsCreateTransform(hLab, TYPE_Lab_DBL, hsRGB, TYPE_RGB_16, INTENT_RELATIVE_COLORIMETRIC, 0);
    cmsHTRANSFORM hForth = cmsCreateTransform(hsRGB, TYPE_RGB_16, hLab, TYPE_Lab_DBL, INTENT_RELATIVE_COLORIMETRIC, 0);

    cmsCloseProfile(hLab);
    cmsCloseProfile(hsRGB);


    maxErr = 0.0;
    for (r = 0; r <= 255; r += 16)
        for (g = 0; g <= 255; g += 16)
            for (b = 0; b <= 255; b += 16)
            {
                seed[0] = rgb[0] = ((r << 8) | r);
                seed[1] = rgb[1] = ((g << 8) | g);
                seed[2] = rgb[2] = ((b << 8) | b);

                for (i = 0; i < 1000; i++)
                {
                    cmsDoTransform(hForth, rgb, &Lab, 1);
                    cmsDoTransform(hBack, &Lab, rgb, 1);
                }

                err = distance(seed, rgb);

                if (err > maxErr)
                    maxErr = err;
            }



    cmsDeleteTransform(hBack);
    cmsDeleteTransform(hForth);

    printf("Maximum sRGB roundtrip error %f\n", maxErr);
    
    return 1;
}
```

**Comment by Lynx3d** [comment] 2021-03-23 14:01
So after a bit of investigation, unquantized vs (poorly) quantized values doesn't seem the actual issue here, while it does make a tiny difference, the pure fact that LCMS' built-in and Elle's ICC profiles aren't 100% identical seems to trigger a nasty precision issue when using 16-bit color spaces, so maybe this is an optimization gone wrong.

Specifically, converting from a linear to an sRGB TRC colorspace in uint16 causes huge errors when the colorants of both profiles aren't identical. Doing it with source in float only produces tiny conversion errors that don't really matter for 8-bit (or even 10 or 12-bit) end results. Also, sRGB TRC => linear seems to be unproblematic in uint16.

Please check this example (pseudo-)code I ripped out of my krita unit test:

```
void uint16toFloat(quint16 *src, float *dst)
{
    for (int i = 0; i < 3; i++) {
        dst[i] = src[i] / 65535.f;
    }
}

void TestProfileGeneration::testProfileCompatibility()
{
    cmsHPROFILE lcms_sRGB = cmsCreate_sRGBProfile();
    cmsHPROFILE elle_sRGB = cmsOpenProfileFromFile("sRGB-elle-V4-srgbtrc.icc", "r");
    cmsHPROFILE elle_linear = cmsOpenProfileFromFile("sRGB-elle-V4-g10.icc", "r");
    cmsHTRANSFORM transform1 = cmsCreateTransform(elle_sRGB, TYPE_RGB_16, elle_linear, TYPE_RGB_16, INTENT_RELATIVE_COLORIMETRIC, cmsFLAGS_HIGHRESPRECALC);
    cmsHTRANSFORM transform2 = cmsCreateTransform(elle_linear, TYPE_RGB_16, lcms_sRGB, TYPE_RGB_16, INTENT_RELATIVE_COLORIMETRIC, cmsFLAGS_HIGHRESPRECALC);
    cmsHTRANSFORM transform2a = cmsCreateTransform(elle_linear, TYPE_RGB_FLT, lcms_sRGB, TYPE_RGB_16, INTENT_RELATIVE_COLORIMETRIC, cmsFLAGS_HIGHRESPRECALC);

    quint16 sourceCol[3] = {43*257, 27*257, 6*257};
    quint16 linearCol[3] = {0};
    float linearColF[3] = {0};
    quint16 finalCol[3] = {0};
    cmsDoTransform(transform1, sourceCol, linearCol, 1);
    cmsDoTransform(transform2, linearCol, finalCol, 1);
    qDebug() << "linearCol: R:" << linearCol[0] << "G:" << linearCol[1] << "B:" << linearCol[2];
    qDebug() << "finalCol: R:" << finalCol[0] << "G:" << finalCol[1] << "B:" << finalCol[2];
    qDebug() << "difference: R:" << (int)sourceCol[0] - finalCol[0]
            << "G:" << (int)sourceCol[1] - finalCol[1] << "B:" << (int)sourceCol[2] - finalCol[2];

    uint16toFloat(linearCol, linearColF);
    cmsDoTransform(transform2a, linearColF, finalCol, 1);
    qDebug() << "finalCol(fp): R:" << finalCol[0] << "G:" << finalCol[1] << "B:" << finalCol[2];
    qDebug() << "difference: R:" << (int)sourceCol[0] - finalCol[0]
            << "G:" << (int)sourceCol[1] - finalCol[1] << "B:" << (int)sourceCol[2] - finalCol[2];
```
The output I get:

```
linearCol: R: 1583 G: 718 B: 119
finalCol: R: 10909 G: 5350 B: 887
difference: R: 142 G: 1589 B: 655
finalCol(fp): R: 11050 G: 6937 B: 1537
difference: R: 1 G: 2 B: 5
```
Maybe you can shed some light on why I get errors >1500 (more than 2% error relative to value range) in uint16 values here, because this clearly shows in 8bits too, this example uses a pretty dark orange/brown and after the conversions it becomes noticeably darker, more saturated, and hue shifted more towards red.

Doing a direct conversion from Elle's sRGB to LCMS' built-in sRGB in uint16 does not show any such huge errors either (we should avoid mixing profiles nevertheless...)

**Comment by mm2** [comment] 2021-03-23 15:07
Ah, ok. This has nothing to do with this arcane pre-quantization, I'm afraid all that info about moving primaries is not very accurate. 

The real issue is about linear spaces and little cms optimization. 

In order to accelerate things, sometimes, lcms performs tetrahedral interpolation when converting colorspaces. This works well when both color spaces are perceptually uniform or both spaces are linear, but works terrible bad when the input space is linear and output is perceptually uniform. Just because in this case the number of contone values assigned to each node is very  non-linear. lcms uses  33 nodes for HIRESPRECALC and almost all got wasted because the linear space encoding. I think you already warns end user in Krita's color management dialog.

The solution is easy: just mark the transforms you do linear->whatever to non-optimizeable, i.e (look at the flags!):
```
    cmsHTRANSFORM transform1 = cmsCreateTransform(elle_sRGB, TYPE_RGB_16, elle_linear, TYPE_RGB_16, INTENT_RELATIVE_COLORIMETRIC, 0);
    cmsHTRANSFORM transform2 = cmsCreateTransform(elle_linear, TYPE_RGB_16, lcms_sRGB, TYPE_RGB_16, INTENT_RELATIVE_COLORIMETRIC, cmsFLAGS_NOOPTIMIZE);
    cmsHTRANSFORM transform2a = cmsCreateTransform(elle_linear, TYPE_RGB_FLT, lcms_sRGB, TYPE_RGB_16, INTENT_RELATIVE_COLORIMETRIC, 0);
```

That should do the trick. It works for me.

```
linearCol: R:1583 G:718 B:119
finalCol: R:11050 G:6937 B:1537
diff: R:1 G:2 B:5
finalCol(fp): R:11050 G:6937 B:1537
diff: R:1 G:2 B:5
```

BTW, nothing prevents you to use linear spaces in the middle of a transformation chain, and you need not to use any special flag in such case. In fact, XYZ is linear and works very well as PCS. The issue is when you want to convert to a **temporary** linear space **using it as storage**. This is often a source of issues.

**Comment by Lynx3d** [comment] 2021-03-25 19:58
> Ah, ok. This has nothing to do with this arcane pre-quantization, I'm afraid all that info about moving primaries is not very accurate.

Yes unfortunately I haven't been able to really reconstruct the whole process of creating those pre-quantized values either.
The presented profiles at least really do seem to lower the error when converting RGB white to L*a*b* white a bit compared to simply rounding each value to the nearest fixed point representation, i.e. values are closer to L*=100, a*=0, b*=0, but if that really makes ICC profiles noticeably better...
The difference doesn't seem dramatic, and of course the original precision you get when creating the color space through LCMS API is still best.

> I think you already warns end user in Krita's color management dialog.

Ah yes you're right, that escaped me...
But thanks for explaining some backgrounds, because now that I look at it, neither the code nor the commits messages really give much of an insight, it just mentions linear color spaces.

As cmsFLAGS_NOOPTIMIZE does not seem to be necessary for float source color spaces, should I not use it in that case, or does it not have any performance impact in that case anyway?

**Comment by mm2** [comment] 2021-03-25 20:57
After further investigation, it happens you hit one of the (rare) cases the optimiser can't resolve satisfactorely. On 8 bits it would optimise well, on float also... but 16 bits + linear spaces does not work and the user has to hint in the flags. I am adding to wish-list  for 2.13 an automatic way to detect and de-activate optimisation when linear encoding + 16 bits is being used.

On floats, optimisation is always off unless you use the plug-in, and in this case it is covered by the plug-in logic. 

Thanks for reporting!

**Comment by mm2** [comment] 2021-06-20 17:46
As promised, by 6b04ee0bab3ebe6f2c487195bac7b86efadd58d3 there is now an automatic detection of linear RGB spaces on 16 bits.

**Comment by mm2** [comment] 2021-09-07 07:43
No issues reported on this, so I'm closing it.

**Closed by mm2** 2021-09-07 07:43 UTC
