### ISSUE TITLE
Fastfloat plugin gives odd results with cLUT carying RGB display profiles

### ISSUE THREAD

**Issue by therahedwig** [mm2/Little-CMS#247] opened 2021-03-10 21:43 UTC
Hi,

In current Krita master, we've got the fastfloat plugin enabled, and it works great with matrix shaper profiles (like, 16bit float is now the slowest bitdepth, as 32bit float is blazing past it!), but I discovered that my display profile, which was generated with Argyll doesn't seem to work with it.

So, in Krita, we split up the image into tiles, which we then separately input into the color conversion. The image to display conversion seems to return broken or completely transparent for some of the tiles we put in, and the results are kinda arbitrary, giving me the feeling like there's a race condition happening somewhere. Once I turn off optimizations, everything works.

![image](https://user-images.githubusercontent.com/1759191/110701817-f0ae7a80-81f1-11eb-8667-97d2527c9d3f.png)

(I cannot identify why some of these images work and some don't, besides that the images that work have 1:1 or 4:3 ratio)

Another thing, which is a little bit more subtle compared to the weird results: The transparency is gone for tiles that did have transparency. Is the copyAlpha flag maybe not taken into account?

I suspect that this has something to do with the fact the display profile has luts, as simple matrix shaper profiles work just fine.

[Here's my display icc profile inside a zip file](https://github.com/mm2/Little-CMS/files/6118965/B139HAN03_0-1.2018-05-17-16-31.2_2-F-S-XYZLUT-MTX.zip)

And [here's where we create our cmsTransforms](https://invent.kde.org/graphics/krita/-/blob/master/plugins/color/lcms2engine/IccColorSpaceEngine.cpp#L43), if that helps.

**Comment by mm2** [comment] 2021-03-11 14:29
Thanks for reporting. I am giving big priority to this issue. Probably will ask you more information, keep in touch.

**Comment by mm2** [comment] 2021-03-21 16:04
Tried hard and I cannot reproduce it. 
Maybe has something to do with compiler's optimization? pointer aliasing?
Your code seems ok, and the profile is ok as well.

**Comment by therahedwig** [comment] 2021-03-21 19:02
I'll ask around during the meeting tomorrow. There's always a chance we're doing something unique with the tiles, or that there's indeed optimizations involved.

**Comment by Lynx3d** [comment] 2021-03-29 15:48
This is just a shot in the dark, but could it have to do with the rather unusual use of BGRA channel order?

It just came to my mind because I noticed the dither formats LCMS offers only include TYPE_RGBA_8_DITHER and TYPE_ABGR_8_DITHER so I was bummed I couldn't try them in krita.

We also see the issue above on soft-proofing btw, and the culprit seems to be 8-bit BGRA input. I tried soft proofing to grayscale/alpha with U8 and U16 input in Lab, XYZ and CMYK color spaces in krita, but only RGB (well, BGRA) gave the alpha issue.

**Comment by mm2** [comment] 2021-03-29 20:41
Thanks I will try to reproduce by using that configuration

**Comment by mm2** [comment] 2021-03-31 08:37
Ongoing. Will retake after easter holidays.

**Comment by therahedwig** [comment] 2021-05-10 13:31
Do you still need anything else from us for this?

**Comment by mm2** [comment] 2021-05-12 17:10
There is a recent commit 31f6546c45a874450903c8635fc2d71893502056 that may solve the issue.
Basically I found that NAN and denormalised values on input could result in weird things. 
It is also possible that the alpha channel you are passing contains such numbers?
If you are so kind to check the development sources, I would appreciate.

**Comment by therahedwig** [comment] 2021-05-26 15:59
Yes, I just build the last commit and the bug is gone. Unless I did something wrong...

**Comment by mm2** [comment] 2021-05-26 17:56
Excellent news!
Thanks for let me know.

**Comment by Lynx3d** [comment] 2021-06-02 09:06
Good that the issue is not closed yet...
I couldn't confirm that the issue is fixed and hence looked some more for possible causes, and I think I finally found it.

Our initial suspicion that cmsFLAGS_COPY_ALPHA is not handled correctly somewhere turned out to be correct. It is in fast_8_tethra.c, it does not increment the out-pointer for the alpha channel, because the loop only iterates over the color channels.

This little patch fixes it for me:

```
diff --git a/plugins/fast_float/src/fast_8_tethra.c b/plugins/fast_float/src/fast_8_tethra.c
index 98601d1..431488f 100644
--- a/plugins/fast_float/src/fast_8_tethra.c
+++ b/plugins/fast_float/src/fast_8_tethra.c
@@ -249,11 +249,13 @@ void PerformanceEval8(struct _cmstransform_struct *CMMcargo,
                                                                *out[OutChan] = FROM_16_TO_8(res16);
                                                                out[OutChan] += DestIncrements[OutChan];
 
-                                                               if (ain)
-                                                                      *out[TotalOut] = *ain;
 
                      }
 
+                     if (ain) {
+                            *out[TotalOut] = *ain;
+                            out[TotalOut] += DestIncrements[TotalOut];
+                     }
 
               }
 
```

fast_16_tethra.c seems correct.
In fast_float_tethra.c I can't find the increment for alpha either though...

**Comment by mm2** [comment] 2021-06-05 14:34
Thanks!
I have done a commit  7f83b09711204dd8166e72544c0178e70d107ad0 with your changes and some other fixes. It seems alpha was completely messed out.

**Comment by Lynx3d** [comment] 2021-06-09 00:27
Looks like the issue is fixed now, works for me and also a user of our nightly builds confirmed that the soft proofing works, so that bug is closed on our end.

Now we can enjoy the nice performance boost :)

**Comment by mm2** [comment] 2021-06-20 09:05
I got no further reports on this issue, so I'm closing it.

**Closed by mm2** 2021-06-20 09:05 UTC
