### ISSUE TITLE
Unable to find program in file system after install

### ISSUE THREAD

**Issue by solanuscasey** [mm2/Little-CMS#440] opened 2024-03-14 01:05 UTC
I'm probably just dumb and missed something, but I installed Little CMS from the website and now I can't find the file to try and open it.(installed from https://www.littlecms.com/color-engine/ on debian 12 bookworm using the provided .Deb file)

**Comment by mm2** [comment] 2024-03-14 08:03
I never hosted packages in the website. You can download and install LittleCMS using the normal packager
https://packages.debian.org/bookworm/liblcms2-2

**Comment by solanuscasey** [comment] 2024-03-14 12:44
The same problem occurs, but I still cant find the files in the system after installing and I don't know what program name I should be using for a terminal launch.

**Comment by mm2** [comment] 2024-03-15 14:41
> I don't know what program name I should be using to launch it from the command line.

No program name at all. This is a software library. You use it when running apps like gimp, krita, colord ...

There are some command line-utilities but those are just helpers. Normally you have those already installed on your Debian
transicc
tificc
jpgicc
psicc

**Comment by mm2** [comment] 2024-03-18 11:17
Closed as it is not a bug

**Closed by mm2** 2024-03-18 11:17 UTC
