### ISSUE TITLE
Endianess regression in cmsMLUtranslationsCodes() from 2.7 to 2.8

### ISSUE THREAD

**Issue by thomas-weber** [mm2/Little-CMS#110] opened 2016-12-11 00:04 UTC
This is Debian bug 847595, https://bugs.debian.org/847595
In 2.7, `cmsMLUtranslationsCodes()` used `_cmsAdjustEndianess16()` to adjust the language and country code for endianess. This is gone in 2.8, where `strFrom16()` is used. That was originally okay, as `strFrom16()` contained an endianess swap/check. But 9fdd8a09563f1f8bbd86def5e1f51d42c4d95f0f dropped that swap. 

As a result, lcms will return ne_SU instead of en_US for the language of a profile; see above mentioned Debian bug for the case of colord's `cd-iccdump` and the test file from https://anonscm.debian.org/git/reproducible/diffoscope.git/plain/tests/data/test1.icc (or lcms' test4.icc). The bug report also contains a [patch](https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=847595;filename=lcms2-fix-strFrom16-byte-order.patch;msg=35), but I am not sure if the patch does just pamper over the problem (there is after all a reason for 9fdd8a09563f1f8bbd86def5e1f51d42c4d95f0f).

**Comment by mm2** [comment] 2016-12-12 22:00
Hopefully Fixed by https://github.com/mm2/Little-CMS/commit/58e1bd7e06f8c98e7d304e4b3ac6c76248be8a1f
If you have a big endian machine, would be nice to do a make check. I left  my old PowerPC when changing job.

**Closed by mm2** 2016-12-12 22:00 UTC

**Comment by thomas-weber** [comment] 2016-12-13 17:28
I have built 58e1bd7e06f8c98e7d304e4b3ac6c76248be8a1f on a PowerPC machine. Unfortunately, `make check` returns an error: "Checking Multilocalized profile ...FAIL!"
I attach the full output of `make check`.
[make-check.txt](https://github.com/mm2/Little-CMS/files/649605/make-check.txt)

**Comment by mm2** [comment] 2016-12-14 21:01
Thanks Thomas for the testing, 

 

Unfortunately, now it is very hard to me to find any big endian platform. Since the issue is fixed for little endian, I will keep this code and revisit it when found any powerpc or something like that. I think this will lower severity of issue.

 

Thanks

Marti

**Comment by mapreri** [comment] 2016-12-17 00:37
I haven't personally tried it (but I can, I have access to both little and big endian machines), but why not using something like the patch that has been posted on the Debian bug tracker, which is (should be?) endian agnostic?

https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=847595;msg=35;filename=lcms2-fix-strFrom16-byte-order.patch

**Comment by thomas-weber** [comment] 2017-12-09 23:34
This issue was finally fixed by 37bed0e57244ccdadeeff150fbf73bd631839bac which in turn fixed issue  https://github.com/mm2/Little-CMS/pull/142
