### ISSUE TITLE
cmsGetPostScriptCSA returns decimals formatted according to locale which breaks PS parsing

### ISSUE THREAD

**Issue by tsdgeos** [mm2/Little-CMS#223] opened 2020-07-05 18:09 UTC
If i'm using a program in Catalan (or any other locale that uses , as decimal separator instead of . like german) calling cmsGetPostScriptCSA gives me stuff like

/BlackPoint [0,000000 0,000000 0,000000]
/WhitePoint [0,964200 1,000000 0,824900]

which is wrong and will make the PS parser unhappy

This is because %f in vsnprintf obeys locale rules as it thinks it's talking to a human instead of to a machine.

As far as i know there's no way to tell printf to do what we want here other than do stuff like

char *old = setlocale(LC_NUMERIC, "C");
printf stuff;
setlocale(LC_NUMERIC, old);

looking at the code i *think* it could work since everything seems to call _cmsIOPrintf which seems likes it's used from cmsps2.c which would imply it's always "talking PS" and never "talking to the user"

Want me to propose a merge request to do that?

**Comment by tsdgeos** [comment] 2020-07-06 21:28
actually setlocale is not that awesome since it changes the locale of the whole app that may not be what other threads want.

If you can depend on posix existing, there's uselocale that is per thread. If you need windows support, i'd suggest just rolling out your own double formatting code like we have in poppler (you can have a look if it's ok for your code to be GPL2+GPL3)

**Comment by mm2** [comment] 2020-07-06 22:00
setlocale is not thread safe and can be very harmful. I will document the behaviour of cmsGetPostScriptCSA and let the end use to decide when revert to default "C" locale before calling postscript generation. Anything other than that would introduce data races. Writing another printf is not an option for a small lib like this one.

**Comment by tsdgeos** [comment] 2020-07-06 22:06
This is a very sad decision.

You're basically making cmsGetPostScriptCSA unusable, because what is the called of cmsGetPostScriptCSA supposed to do?

You can actually fix it properly by having your own double formatting code, the caller of cmsGetPostScriptCSA can't.

**Comment by tsdgeos** [comment] 2020-07-06 22:36
How do you feel about this? (needs applying to more places)

It's a bit lame but should fix the problems and not be super CPU-time consuming

```
diff --git a/src/cmsps2.c b/src/cmsps2.c
index d101e8d..511ff24 100644
--- a/src/cmsps2.c
+++ b/src/cmsps2.c
@@ -358,6 +358,22 @@ void EmitHeader(cmsIOHANDLER* m, const char* Title, cmsHPROFILE hProfile)
 
 }
 
+static
+char *format_doubles_ensure_dots(const char *fmt, ...)
+{
+    va_list argList, argList2;
+    va_start(argList, fmt);
+    va_copy(argList2, argList);
+    size_t needed = vsnprintf(NULL, 0, fmt, argList) + 1;
+    char  *buffer = malloc(needed);
+    vsprintf(buffer, fmt, argList2);
+    for (int i = 0; i < needed; ++i) {
+        if (buffer[i] == ',') buffer[i] = '.';
+    }
+    va_end(argList2);
+    va_end(argList);
+    return buffer;
+}
 
 // Emits White & Black point. White point is always D50, Black point is the device
 // Black point adapted to D50.
@@ -365,14 +381,15 @@ void EmitHeader(cmsIOHANDLER* m, const char* Title, cmsHPROFILE hProfile)
 static
 void EmitWhiteBlackD50(cmsIOHANDLER* m, cmsCIEXYZ* BlackPoint)
 {
+    char *blackPoint = format_doubles_ensure_dots("%f %f %f", BlackPoint -> X, BlackPoint -> Y, BlackPoint -> Z);
 
-    _cmsIOPrintf(m, "/BlackPoint [%f %f %f]\n", BlackPoint -> X,
-                                          BlackPoint -> Y,
-                                          BlackPoint -> Z);
+    _cmsIOPrintf(m, "/BlackPoint [%s]\n", blackPoint);
 
     _cmsIOPrintf(m, "/WhitePoint [%f %f %f]\n", cmsD50_XYZ()->X,
                                           cmsD50_XYZ()->Y,
                                           cmsD50_XYZ()->Z);
+
+    free(blackPoint);
 }
 
 

```

**Comment by mm2** [comment] 2020-07-06 23:00
That could work.
I have some (bad) exprerience on setlocale. To me, anything but the "C" default is basically broken. Code that otherwise would  nicely be portable gets more and more complexity and issues and all is caused by setlocale. Embedded doesn't work or just crashes on  some combinations. On the other hand, sprintf does nice things on float point precission, some of those are not easely portable, so sprintf is a great helper. Your solution may seem a little bit hackish, but I like it. Does its job, solves the issue nicely and  without side effects, so thank you so much, i will integrate  this code in a day or two.
Regards
M.

**Comment by mm2** [comment] 2020-07-07 16:40
fixed by bde08cc2a8972f17cf1f00082e413e0934625afd

**Closed by mm2** 2020-07-07 16:40 UTC

**Comment by tsdgeos** [comment] 2020-07-07 21:33
Are you 100% sure that things that end up in _cmsIOPrintf can't have commas?

There seem to be some stuff that is %s, i.e. normal text, we wouldn't want to fix decimals and then break something else that actually expected to have a , in there ^_^

**Comment by tsdgeos** [comment] 2020-07-07 21:34
And i just saw the comment saying "no commas are needed", so i guess you checked :)

Thanks, i guess i can apply a similar temporary fix in poppler
